name: Test

run-name: ${{ github.actor }} is testing the app

on:
  workflow_dispatch:
  push:
    branches:
      - 'interval-type'
    
  # pull_request:
  #   types:
  #     - opened
  #     - reopened
  #     - synchronize
  #     - ready_for_review
  #   branches:
  #     - 'main'
  #   paths-ignore:
  #     - '**.md'
  #     - '**.yaml'
  #     - 'doc/**'
  #     - '.git/'
  #     - '.vscode/'

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm
      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 35
          arch: x86_64
          script: flutter emulators
          # script: flutter run -t ./test/widget_test.dart
          working-directory: example
      # - run: flutter pub get
      #   working-directory: example
      # - run: flutter test
      #   working-directory: example

# jobs:
#   test:
#     runs-on: ubuntu-latest
#     steps:
#       - name: checkout
#         uses: actions/checkout@v4

#       - name: Enable KVM
#         run: |
#           echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
#           sudo udevadm control --reload-rules
#           sudo udevadm trigger --name-match=kvm

#       - name: run tests
#         uses: reactivecircus/android-emulator-runner@v2
#         with:
#           api-level: 29
#           script: flutter run -t ./example/test/widget_test.dart 